In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Making the dataset

In [111]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

In [112]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [113]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [114]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=4)

In [115]:
#Model Training

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()

log_reg.fit(X_train, y_train)

LogisticRegression()

In [116]:
y_pred = log_reg.predict(X_test)
print(y_pred)

[1 1 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1
 1 1 0 1 1 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0 0 1 0 1 1 1 1 1
 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 0 1 0 0
 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 0 1 1
 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1
 0 1 0 1 1 0 1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 0 1 0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 0
 1 0 1 1]


In [117]:
log_reg.predict_proba(X_test)

array([[9.82264785e-02, 9.01773522e-01],
       [7.81025103e-02, 9.21897490e-01],
       [7.74041199e-01, 2.25958801e-01],
       [8.78981156e-01, 1.21018844e-01],
       [6.80856576e-03, 9.93191434e-01],
       [9.88755563e-01, 1.12444371e-02],
       [6.07791554e-02, 9.39220845e-01],
       [6.69163515e-02, 9.33083648e-01],
       [9.90172003e-01, 9.82799687e-03],
       [5.74508642e-01, 4.25491358e-01],
       [3.58549900e-01, 6.41450100e-01],
       [9.60374342e-01, 3.96256581e-02],
       [8.90288549e-01, 1.09711451e-01],
       [9.85369245e-01, 1.46307548e-02],
       [3.01501299e-01, 6.98498701e-01],
       [1.36678321e-02, 9.86332168e-01],
       [9.67106530e-01, 3.28934704e-02],
       [4.65467826e-01, 5.34532174e-01],
       [1.55539816e-01, 8.44460184e-01],
       [7.53787792e-01, 2.46212208e-01],
       [6.78005714e-01, 3.21994286e-01],
       [9.40472387e-01, 5.95276128e-02],
       [9.51984795e-01, 4.80152050e-02],
       [4.12670084e-01, 5.87329916e-01],
       [9.127919

## Metrics


In [118]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Score: ", score)
print("Confusion Matrix: \n", cm)
print("Classification Report: \n",report)

Score:  0.8766666666666667
Confusion Matrix: 
 [[131  21]
 [ 16 132]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.89      0.86      0.88       152
           1       0.86      0.89      0.88       148

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



## Hyperparameter Tuning

In [119]:
model = LogisticRegression()

penalty = ['l1', 'l2', 'elasticnet']
c_values = [100, 10, 1,0.1,0.001]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

params = dict(penalty=penalty, C = c_values, solver = solver)

### Grid Search CV

In [120]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

cv = StratifiedKFold()

grid = GridSearchCV(estimator=log_reg, param_grid=params, scoring='accuracy', cv = cv, n_jobs= -1)

In [121]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [122]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')


In [123]:
grid.fit(X_train, y_train)

/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [124]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}

In [125]:
grid.best_score_

np.float64(0.8600000000000001)

In [126]:
y_pred = grid.predict(X_test)

score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Score: ", score)
print("Confusion Matrix: \n", cm)
print("Classification Report: \n",report)

Score:  0.88
Confusion Matrix: 
 [[132  20]
 [ 16 132]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.89      0.87      0.88       152
           1       0.87      0.89      0.88       148

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



### Random Search Hyper-parameter Tuning

In [127]:
from sklearn.model_selection import RandomizedSearchCV

randomCV = RandomizedSearchCV(estimator=log_reg, param_distributions=params, cv = 5, scoring='accuracy')
randomCV

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.001],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [128]:
randomCV.fit(X_train, y_train)

/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/sanket/Desktop/Code/python/ml/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sanket/Desktop/Code/py

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.001],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [129]:
y_pred = randomCV.predict(X_test)

score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Score: ", score)
print("Confusion Matrix: \n", cm)
print("Classification Report: \n",report)

Score:  0.88
Confusion Matrix: 
 [[132  20]
 [ 16 132]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.89      0.87      0.88       152
           1       0.87      0.89      0.88       148

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



In [130]:
randomCV.best_score_

np.float64(0.8600000000000001)

In [131]:
randomCV.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}